### PR TITLE
Binary

### PR DESCRIPTION
**Pull request by JiviteshDebata**
Makes the file non human readable

### CODE REVIEW

**Comment by JiviteshDebata** [comment]
Complete SHA implemented. Hash generated can be used for any purpose

**Comment by americast** [comment]
Hi @JiviteshDebata! Thanks a lot for this. :+1:
Please rebase with `master`. Also, do mention which issue your PR fixes, with something like `fixes #<issue no.>`.

**Comment by americast** [comment]
@JiviteshDebata Can you please reference the issue you are attempting to fix? Thanks!

**Comment by JiviteshDebata** [comment]
Issue has been closed
Sorry for the radio silence but i lost internet and my phone ;_;
Back now.

**Pull request closed without merging**
