### PR TITLE
Added ScoreBoard Using Open CV

### PR DESCRIPTION
**Pull request by shan7030**
#24 Issue Resolved . This will display the Score on Window

### CODE REVIEW

**Comment by shan7030** [comment]
Let's merge it!!

**Comment by shan7030** [comment]
Let's merge it now !!

**Comment by americast** [comment]
Hi @shan7030, could you post some screenshots here?

**Comment by shan7030** [comment]
Yes !!

**Comment by shan7030** [comment]
screenshot from 2019-03-01 12-54-02

**Comment by americast** [comment]
@shan7030 Thanks! :slightly_smiling_face: : 
Could you please remove this file `.vscode/c_cpp_properties.json` from the PR?
Also let's not congratulate someone when the score is zero :sweat_smile:

**Comment by shan7030** [comment]
Changes done Successfully ! Let's merge it now!

**Pull request closed without merging**
